services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mitra
      POSTGRES_PASSWORD: mitra
      POSTGRES_DB: mitra
    ports:
      - '5432:5432'
    volumes:
      - mitra_postgres_data:/var/lib/postgresql/data

volumes:
  mitra_postgres_data:
